name: Build Windows Binary

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          ruby-version: '3.3'
      - name: Install ocra
        run: gem install ocra
      - name: Build Binary
        run: ocra orconverter.rb --no-autoload --gem-full=i18n
