name: Build Windows Binary

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'head'
      - name: Install dependencies
        run: bundle install
      - name: Install ocra
        run: gem install ocra
      - name: Build Binary
        run: ocra orconverter.rb --no-autoload --gem-full=i18n
